[package]
name = "pentago"
version = "0.1.0"
edition = "2024"

[lib]
name = "pentago_engine"
crate-type = ["rlib", "cdylib"]

[[bin]]
name = "pentago"
path = "src/pentago.rs"

[features]
default = []
python_binding = ["dep:pyo3"]

[dependencies]
ico = "0.4"
image = "0.24"
macroquad = "0.4.14"
pyo3 = { version = "0.29", features = ["extension-module"], optional = true }
